workflows:
  ios-native-workflow:
    name: iOS Native
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.settlemate.nz
      vars:
        BUNDLE_ID: com.settlemate.nz
        XCODE_WORKSPACE: "CodemagicSample.xcworkspace" # <-- Update to your actual .xcworkspace name if different
        XCODE_SCHEME: "CodemagicSample" # <-- Update to your actual scheme name if different
        APP_STORE_APPLE_ID: 6817467746
      xcode: latest
    scripts:
      - name: Install Node dependencies
        script: |
          npm install
      - name: Set up provisioning profiles settings on Xcode project
        script: xcode-project use-profiles
      - name: Build ipa for distribution
        script: | 
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - aditya@uniwidetech.com
          - precisedcom@gmail.com
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - group name 1
          - group name 2
        submit_to_app_store: true
